"""Add workspace, product, workspace_page models and conversation updates

Revision ID: b1edf68c1ae4
Revises: 
Create Date: 2025-12-05 06:50:42.333574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1edf68c1ae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create workspaces table
    op.create_table('workspaces',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('ad_account_id', sa.String(length=36), nullable=True),
        sa.Column('default_daily_budget', sa.Float(), nullable=True),
        sa.Column('default_currency', sa.String(length=10), nullable=True),
        sa.Column('default_objective', sa.String(length=50), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('facebook_connected', sa.Boolean(), nullable=True),
        sa.Column('setup_completed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create workspace_pages table
    op.create_table('workspace_pages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workspace_id', sa.String(length=36), nullable=False),
        sa.Column('facebook_page_id', sa.String(length=36), nullable=False),
        sa.Column('default_tone', sa.String(length=50), nullable=True),
        sa.Column('default_cta_style', sa.String(length=50), nullable=True),
        sa.Column('target_markets', sa.JSON(), nullable=True),
        sa.Column('is_included', sa.Boolean(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['facebook_page_id'], ['facebook_pages.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_id', 'facebook_page_id', name='uq_workspace_page')
    )

    # Create products table
    op.create_table('products',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workspace_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('short_description', sa.Text(), nullable=True),
        sa.Column('long_description', sa.Text(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('price_range_min', sa.Float(), nullable=True),
        sa.Column('price_range_max', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('usp', sa.Text(), nullable=True),
        sa.Column('target_audience', sa.Text(), nullable=True),
        sa.Column('seasonality', sa.String(length=100), nullable=True),
        sa.Column('primary_image_url', sa.String(length=500), nullable=True),
        sa.Column('image_url_2', sa.String(length=500), nullable=True),
        sa.Column('image_url_3', sa.String(length=500), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create page_products table
    op.create_table('page_products',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workspace_page_id', sa.String(length=36), nullable=False),
        sa.Column('product_id', sa.String(length=36), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_page_id'], ['workspace_pages.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('workspace_page_id', 'product_id', name='uq_page_product')
    )

    # Add columns to existing tables
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('workspace_page_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('chat_type', sa.Enum('ACCOUNT_OVERVIEW', 'PAGE_WAR_ROOM', 'LEGACY', name='conversationtype'), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archive_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pinned_content', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'workspace_pages', ['workspace_page_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_workspace_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_user_active_workspace', 'workspaces', ['active_workspace_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_active_workspace', type_='foreignkey')
        batch_op.drop_column('active_workspace_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pinned_content')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('archive_summary')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')
        batch_op.drop_column('chat_type')
        batch_op.drop_column('workspace_page_id')
        batch_op.drop_column('workspace_id')

    # Drop new tables
    op.drop_table('page_products')
    op.drop_table('products')
    op.drop_table('workspace_pages')
    op.drop_table('workspaces')

    # ### end Alembic commands ###
