"""Add active_product_id to conversations

Revision ID: c2fda79d2be5
Revises: b1edf68c1ae4
Create Date: 2025-12-05 08:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fda79d2be5'
down_revision = 'b1edf68c1ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_product_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            'fk_conversation_active_product',
            'products',
            ['active_product_id'],
            ['id'],
            ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_active_product', type_='foreignkey')
        batch_op.drop_column('active_product_id')
    # ### end Alembic commands ###
